### ISSUE TITLE
multi language does not work

### ISSUE THREAD

**Issue by mreza9** [andresaraujo/timeago.dart#102]
multi-language does not work and returns only English.

in src\timeago.dat please add other languages. (now added en and es only)

Map<String, LookupMessages> _lookupMessagesMap = {
  'en': EnMessages(),
  'en_short': EnShortMessages(),
  'es': EsMessages(),
  'es_short': EsShortMessages(),
  'fr': FrMessages(),
};

I added fr language.

**Comment by topex-psy** [comment]
you can initalize your class with this code, for example for Indonesian language:

```
timeago.setLocaleMessages('id', timeago.IdMessages());
```
