### ISSUE TITLE
Cannot set locale to khmer language 

### ISSUE THREAD

**Issue by Virakyuth-PK** [andresaraujo/timeago.dart#104]

**Comment by MRSEREY** [comment]
@Virakyuth-PK try this:

final fifteenAgo = new DateTime.now().subtract(new Duration(minutes: 15));
timeago.setLocaleMessages('km', timeago.KmMessages());

print(timeago.format(fifteenAgo, locale: 'km'));    // មុននេះ​ 15 នាទី

but to me, I think the translation sound a bit weird to me it should be 15 នាទីមុន

**Comment by Virakyuth-PK** [comment]
Thank you 😊
