### ISSUE TITLE
Release new version timeago_flutter (the widget)?

### ISSUE THREAD

**Issue by paxcodes** [andresaraujo/timeago.dart#110]
There's 2 commits from @kranfix for the widget but it hasn't been released to pub.dev

How can I help release a new version of timeago_flutter? If I make a PR with similar changes as in commits like [this](https://github.com/andresaraujo/timeago.dart/commit/5f492e21e8a47da7d13a58e641e5cbc69c919832), will that help?

**Comment by kranfix** [comment]
Ok

**Comment by paxcodes** [comment]
Hey @kranfix thank you for responding so quickly. By "Ok",  do you mean:

a) "Yes, @paxcodes, go ahead and make a PR" _or_ 
b) "I, @kranfix, will make a release in pub.dev"

**Comment by kranfix** [comment]
It means that I will send the PR later. I have no uploader permissions.

**Comment by paxcodes** [comment]
Alright. Thank you, @kranfix ! Hopefully @andresaraujo would have the time to upload in pub.dev 🙏🏼

Thank you both for the great package. 👏🏼

**Comment by andresaraujo** [comment]
Thanks, sorry for the delay, just published v0.2! @kranfix @paxcodes 

It could be great if anyone could help update the flutter widget readme @kranfix

**Comment by paxcodes** [comment]
@andresaraujo I could help with creating the README! I need to understand first how it works as I'm running into [an issue](https://github.com/andresaraujo/timeago.dart/issues/111). I think it's a bug but it could also be that I'm using the widget incorrectly.

**Comment by kranfix** [comment]
@andresaraujo please publish both `timeago` and `timeago_flutter`.
