### ISSUE TITLE
pt_BR localizations

### ISSUE THREAD

**Issue by Panthro** [andresaraujo/timeago.dart#12]
Just a friendly reminder to myself to create a PR to add this.

(or if anyone does it first).

**Comment by ateodor1** [comment]
Could you please update the project with pt_BR ? I noticed it is already created but not available yet... Thanks.

**Comment by Panthro** [comment]
Not done yet, it's in my todo list, before launching the app I'm building I have to do it xD.

Feel free to start a PR if you want to

**Comment by Panthro** [comment]
There's already a PR for that #13  by @jeanpimentel 

@andresaraujo  can you check/merge that PR?

**Comment by andresaraujo** [comment]
Thanks! I just released 1.2.2 with Portuguese translations 
https://pub.dartlang.org/packages/timeago/versions/1.2.2
