### ISSUE TITLE
timeago

### ISSUE THREAD

**Issue by alihassan143** [andresaraujo/timeago.dart#123]
timeago is not working in flutter in vs code

**Comment by kranfix** [comment]
It is working for me.  Can you provide more information:  
  
\- Your Dart SDK version in your Pubspec.  
\- The Flutter version you have installed.  
\- The error message.

**Comment by alihassan143** [comment]
actually i am not using timeago correctly error is solved my mistake 
in import i have to import timeago as timeago i am directly calling the timeago function that is not correct way
