### ISSUE TITLE
timeago_flutter published?

### ISSUE THREAD

**Issue by jasonlaw** [andresaraujo/timeago.dart#125]
Hi,

May I know is timeago_flutter published?
I am using the latest verson 2.0.29 but doesn't seems to find the timeago_flutter.

Thanks.

**Comment by kranfix** [comment]
This is the published package.  
https://pub.dev/packages/timeago_flutter  
  
Or what are you talking about?

**Comment by jasonlaw** [comment]
> This is the published package.
> https://pub.dev/packages/timeago_flutter
> 
> Or what are you talking about?

That's exactly what I am looking for, thank you very much!
