### ISSUE TITLE
changing the local property doesn't make any change 

### ISSUE THREAD

**Issue by F-BONAPARTA** [andresaraujo/timeago.dart#135]
here is my code 
![image](https://user-images.githubusercontent.com/67749770/107306961-81c4f100-6a8e-11eb-9b2c-95f0a1d4bb9e.png)
and the emulator :
![image](https://user-images.githubusercontent.com/67749770/107307006-9608ee00-6a8e-11eb-8503-afd2d0b06e4a.png)
note: i wrap my widget in directionalty

**Comment by Schnodderbalken** [comment]
Same here. Localization does not affect the output at all. Only works for English language at the moment.

**Comment by andresaraujo** [comment]
Did you enabled the `ar` locale? like in this example? https://github.com/andresaraujo/timeago.dart/blob/master/timeago/example/main.dart#L51

**Comment by Schnodderbalken** [comment]
Oh, my bad. If I do it like you suggest @andresaraujo, it works. Thank you!

**Comment by F-BONAPARTA** [comment]
@andresaraujo  oh i forgot that, thanks
