### ISSUE TITLE
pt_BR seems to be not working

### ISSUE THREAD

**Issue by ateodor1** [andresaraujo/timeago.dart#14]
I tested the new locale 'pt_BR' but it still showing the default english locale...

timeAgo(date, locale: 'pt_BR')
is showing '21 hours ago'

I confirmed it is getting from the last release 

Can you please confirm the pt_BR is working properly ? Thanks.

**Comment by andresaraujo** [comment]
Fixed in 4a1b2f8ddb97903cabb72d00bd183be53a1eb818

1.2.3 released in pub
