### ISSUE TITLE
Update live demo to include all available messages

### ISSUE THREAD

**Issue by andresaraujo** [andresaraujo/timeago.dart#172]
Now that the `timeago_flutter_example`will be used for the live demo we should add all the available locales into that demo.

**Scope**

- Setup your local dev environment see README's local development

- Open `packages/timeago_flutter_example/lib/main.dart` add all the available locales from the core package (See `packages/timeago/lib/timeago.dart`)
- Run the fluetter example locally and verify it displays the locales

**Comment by tlindi** [comment]
Someone has done something. Demo has changed its look. fi and fi_short works now. et-EE still missing.

**Comment by EltonLi2000** [comment]
Hi team, I've updated the examples project to include more locales. Please have a look when you can, thanks.
https://github.com/andresaraujo/timeago.dart/pull/191

**Comment by andresaraujo** [comment]
closed in #191
