### ISSUE TITLE
Fix german translations

### ISSUE THREAD

**Issue by tsdevelopment** [andresaraujo/timeago.dart#19]
Please fix german translations as follows:

`vor x Tage` must be `vor x Tagen`

There is a missing `n` at the end of plural strings.

**Comment by andresaraujo** [comment]
Thanks! Fixed in 1.2.7 release @tsdevelopment

**Comment by tsdevelopment** [comment]
Thank you for the fix, but I meant that there are multiple strings to fix. Same thing in `Monate` and `Jahre`. Must be `Monaten` and `Jahren.` Sorry, I only wrote it for the days string.

**Comment by andresaraujo** [comment]
Oh I see, will make those change in the next release thanks for reporting

**Comment by tsdevelopment** [comment]
You released several times a new version of your library. Is it possible to fix the translations in one of your next releases?

**Comment by andresaraujo** [comment]
Hi @tsdevelopment , I don't speak German, could you review this pr to see if this is enough?
https://github.com/andresaraujo/timeago.dart/pull/30

**Comment by tsdevelopment** [comment]
I commented your PR. Only one small fix. Thank you very much!

**Comment by andresaraujo** [comment]
Just released 2.0.5 @tsdevelopment that fixes this

Thanks
