### ISSUE TITLE
Any plans to make this library dart 2 compatible?

### ISSUE THREAD

**Issue by martflu** [andresaraujo/timeago.dart#22]

**Comment by mit-mit** [comment]
Yes, looks like the the Dart SDK constraint needs to be updated to [declare compatibility with Dart 2 stable]:
https://github.com/andresaraujo/timeago.dart/blob/master/pubspec.yaml#L9

cc @andresaraujo

**Comment by enyo** [comment]
See https://github.com/andresaraujo/timeago.dart/pull/23

**Comment by andresaraujo** [comment]
Fixed in v1.3.0
