### ISSUE TITLE
More resolution for times under a minute

### ISSUE THREAD

**Issue by hoylen** [andresaraujo/timeago.dart#3]
Instead of always saying, "just a moment ago" for anything under one minute, can it break up that period into several different texts?

When showing the progress of an activity, the user might think nothing is happening if it always said the same thing for the first minute. They are going to get impatient if nothing changes before a minute. Or the text is not going to be useful if the task only takes about a minute to run.

Suggest more fine grain durations like:
- just a moment ago
- about 5 seconds ago
- about 10 seconds
- 15, 25, 30, 40 50
- about 1 minute ago

**Comment by andresaraujo** [comment]
Just published v2(read readme and examples) let me know if have any issues
