### ISSUE TITLE
export LookupMessages type

### ISSUE THREAD

**Issue by shrugs** [andresaraujo/timeago.dart#37]
### Current Behavior:

In order to implement LookupMessage and call `setLocaleMessages` for custom locales or custom locales, we must currently import an implementation file, which the analyzer complains about.

### Solution

export LookupMessage as part of the top-level timeago library.

### Workaround

```dart
// ignore_for_file: implementation_imports

import 'package:timeago/timeago.dart' as timeago;
import 'package:timeago/src/messages/lookupmessages.dart';

class MyCustomLookupMessages implements LookupMessages {
  // ...
}

// ...

timeago.setLocaleMessages("custom", MyCustomLookupMessages());
```

**Comment by andresaraujo** [comment]
Thanks @shrugs ! This is implemented in version 2.0.10
