### ISSUE TITLE
Change request for JaMessages class

### ISSUE THREAD

**Issue by mitsuoka** [andresaraujo/timeago.dart#41]
Japanese counter characters for number of months is complex. See : [HOW TO USE THE JAPANESE COUNTER 箇月 (かげつ)](https://www.tofugu.com/japanese/japanese-counter-tsuki-gatsu-getsu/#how-to-use-the-japanese-counter---1)

But using hiragana ‘か’ instead of ‘個’ is most common. I think expressing like ‘か月’ for number of month(s) is the best fit for contemporary Japanese. 

Please replace ‘月’ with ‘か月’ in the line 15 and 16 of the file : timeago.dart/timeago/lib/src/messages/ja_messages.dart
as :

import 'package:timeago/src/messages/lookupmessages.dart';

class JaMessages implements LookupMessages {
  String prefixAgo() => '';
  String prefixFromNow() => '今から';
  String suffixAgo() => '前';
  String suffixFromNow() => '後';
  String lessThanOneMinute(int seconds) => '1 分未満e';
  String aboutAMinute(int minutes) => '約 1 分';
  String minutes(int minutes) => '$minutes 分';
  String aboutAnHour(int minutes) => '約 1 時間';
  String hours(int hours) => '約 $hours 時間';
  String aDay(int hours) => '約 1 日';
  String days(int days) => '約 ${days} 日';
  String aboutAMonth(int days) => '約 1 か月';
  String months(int months) => '約 ${months} か月';
  String aboutAYear(int year) => '約 1 年';
  String years(int years) => '約 ${years} 年';
  String wordSeparator() => ' ';
}

**Comment by andresaraujo** [comment]
Thanks @mitsuoka  for reporting this, I created a PR can you review if this is what you meant? https://github.com/andresaraujo/timeago.dart/pull/46

**Comment by mitsuoka** [comment]
Yes, please incorporate this change into your package.
