### ISSUE TITLE
Why there is no Readme file?

### ISSUE THREAD

**Issue by ammaratef45** [andresaraujo/timeago.dart#44]
I think you should add a readme file that explains usage and contribution, maybe more :+1:

**Comment by andresaraujo** [comment]
There is! its in https://github.com/andresaraujo/timeago.dart/tree/master/timeago for the library, flutter widget is a work in progress 

I need to add one to the root

**Comment by andresaraujo** [comment]
Added a read to the root, I hope its more clear now
