### ISSUE TITLE
nl messages lessThanOneMinute() contains the suffix found in suffixAgo()

### ISSUE THREAD

**Issue by soowa** [andresaraujo/timeago.dart#49]
In nl_messages.dart, `lessThanOneMinute()` contains the suffix found in `suffixAgo()` leading to a semantically incorrect message like: `een moment geleden geleden` where the second `geleden` should have been omitted.

**Comment by andresaraujo** [comment]
@soowa If you could create the PR I'll happily merge it :)

**Comment by soowa** [comment]
@adresaraujo I created a pull request related to this issue.

**Comment by andresaraujo** [comment]
Fixed in v2.0.16
