### ISSUE TITLE
how to remove "ago" ?

### ISSUE THREAD

**Issue by HoneyBadger9** [andresaraujo/timeago.dart#57]
i.e from "5 minutes ago" to "5 minutes".

**Comment by andresaraujo** [comment]
One solution if you want to remove the 'ago' suffix in the english locale, is to create a class that extends `EnMessages` and override the `suffixAgo` method like this:

```dart
import 'package:timeago/timeago.dart' as timeago;

class CustomEn extends timeago.EnMessages {
  @override
  String suffixAgo() => '';
}

main() {
  // This will override `en` locale with the custom messages
  timeago.setLocaleMessages('en', CustomEn());
}
```

**Comment by EmmanuelOgbewe** [comment]
Is it also possible to override minutes and say "2 min" ?

**Comment by tyl0r** [comment]
> Is it also possible to override minutes and say "2 min" ?

Using the example above, you would just do add this to your custom class:
`String minutes(int minutes) => '$minutes min';`

For example:

```
import 'package:timeago/timeago.dart' as timeago;

class CustomEn extends timeago.EnMessages {
  @override
  String suffixAgo() => '';
  String minutes(int minutes) => '$minutes min';
}

main() {
  // This will override `en` locale with the custom messages
  timeago.setLocaleMessages('en', CustomEn());
}
```

**Comment by kranfix** [comment]
Review `timeago.EnShortMessages` instead of `timeago.EnMessages`.
