### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by erf** [andresaraujo/timeago.dart#58]
The following languages are missing localization:
- hindi hi
- swedish sv
- finnish fi

There are probably many more localizations missing. 

We could perhaps make a script using the Google Cloud Translation API, to translate for all languages.

**Comment by rostopira** [comment]
Russian ru is also missing (the only one I actually needed \*sigh\*)

**Comment by andresaraujo** [comment]
Maybe we can use some already popular library that has lot of supported languages and use them as reference, that would be easier.

**Comment by hiashutoshsingh** [comment]
I can take the hindi(hi) translations @andresaraujo

**Comment by andresaraujo** [comment]
Release v2.0.28 includes hindi support @erf @hiashutoshsingh
