### ISSUE TITLE
Update version dependency on intl package

### ISSUE THREAD

**Issue by hoylen** [andresaraujo/timeago.dart#6]
In **timeago** release v1.0.1, the dependency on **intl** `>=0.12.2 <0.15.0` is preventing the newer version 0.15.0 of _intl_ from being used.

**Comment by andresaraujo** [comment]
Thanks for pointing out this 😄

**Comment by andresaraujo** [comment]
fixed in fb271a2922e1dbfcd9365ffe21538e9741353802
