### ISSUE TITLE
Flutter auto update timeAgo.

### ISSUE THREAD

**Issue by uwejan** [andresaraujo/timeago.dart#72]
Hello, this is not an issue, its more of how to, using flutter how do i have the feeling of time ago auto increment by time?
right now i dot as follow;
```import 'package:timeago/timeago.dart' as timeago;
                    var time = timeago.format(date,allowFromNow: true,clock:timeStamp );
```
Thank you.

**Comment by AnasSafi** [comment]
What (timeStamp) mean? timeStamp is Integer and clock accept only Datetime...!

I solve it by using **Timer.periodic** ...

**Comment by paxcodes** [comment]
No need to implement `Timer.periodic....` yourself. The package has a widget include that does exactly what you need: [`Timeago`](https://github.com/andresaraujo/timeago.dart/blob/master/timeago_flutter/lib/timeago_flutter.dart)

Interestingly, it is not in the package's `README`'s `Usage` section.

**Comment by paxcodes** [comment]
Looks like the author published it as a separate package https://pub.dev/packages/timeago_flutter
