### ISSUE TITLE
date conversion error

### ISSUE THREAD

**Issue by Julianojc** [andresaraujo/timeago.dart#76]
I am receiving this answer from my API -> 1994-02-22 00: 00: 00.000 , but when using the plugin for conversion, I have the answer "26 years", 1 year longer than the correct one ... I only get the correct conversion when timestamp months are higher than month 06.

**Comment by andresaraujo** [comment]
Can you provide sample code I can look at?

**Comment by kranfix** [comment]
Your publication was on Nov 11, 2019. The api date is Feb 22, 1994.  
  
The Duration difference is: 25 years 8 month and 19 days. This is rounded to 26 years. Then @Julianojc  has reason.

```dart
result = messages.years(years.round())
```

**Comment by kranfix** [comment]
This is related to #47
