### ISSUE TITLE
Version solving failed.

### ISSUE THREAD

**Issue by charkala** [andresaraujo/timeago.dart#77]
Need support for `intl ^0.16.0`, I get the following error:

```
Because timeago ^1.3.0 depends on intl ^0.15.1 and my_app depends on intl ^0.16.0, timeago ^1.3.0 is forbidden.
```

My current workaround is using `intl ^0.15.1`.

Will there be an update to the package?

**Comment by andresaraujo** [comment]
v1 is not longer maintained, I would suggest to migrate to v2 if possible
