### ISSUE TITLE
Testability: Allow a fake `new DateTime.now()`

### ISSUE THREAD

**Issue by matanlurey** [andresaraujo/timeago.dart#9]
Idea:

```dart
class TimeAgo {
  TimeAgo({String locale, DateTime Function() clock}) {
    this.locale = locale;
    this.clock = clock ?? () => new DateTime.now();
  }

  // ... and use clock below ...
}
```

If you agree with this, let me know, and I can send a PR :)

**Comment by andresaraujo** [comment]
Hi @matanlurey, sure I like the idea. 

By the way what are your thoughts on the API? I might rework/ make it cleaner for 2.0+

**Comment by andresaraujo** [comment]
Just published v2(read readme and examples) let me know if have any issues
