### ISSUE TITLE
timeago 2.0.26 requires SDK version >=2.6.0 <3.0.0

### ISSUE THREAD

**Issue by goldyonwar** [andresaraujo/timeago.dart#93]
The current Dart SDK version is 2.5.0.
Because timeago 2.0.26 requires SDK version >=2.6.0 <3.0.0 and no versions of timeago match >2.0.26 <3.0.0, timeago ^2.0.26 is forbidden.

**Comment by marcelgarus** [comment]
In fact, the current Dart version is 2.7.0, so you can probably resolve this issue by upgrading your Dart runtime.
Either way, the code in the package doesn't utilize the newest features of Dart, like extension methods, so it would be better if this package would depend on Dart >=2.5.0 <3.0.0.
