### ISSUE TITLE
Can I use limit?

### ISSUE THREAD

**Issue by taz1208** [andresaraujo/timeago.dart#95]
Hi
it's so wonderful
but I want set range

for example

Before 7days => 5m, 7days ago (etc..)
After 7days => 2020-03-26 08:13,  2020-03-26 (or some other format)

Can I ?

**Comment by marcelgarus** [comment]
Nope, that's not possible with the current architecture 😞
Only a complete rewrite to a more customizable architecture, perhaps like proposed in #94, would make this possible.

**Comment by kranfix** [comment]
@marcelgarus could you add this approach to your suggestion in #94, please?
